#!/usr/bin/env bash
#
# This helper script is generated by ansible
#
# @author Tobias Schifftner, @tschifftner


{% for helper in project.helper %}
function {{ helper.name }} {
    echo -e "\e[93m"
    (cd / && {{ helper.command }})
    echo -e "\e[0m"
}
{% endfor %}

# run script
if [ `type -t $1`"" == 'function' ]; then
    $1
else
    echo -e "
    \e[91m{{ project.name }} ({{ project.environment }})\e[0m - helper script

    USAGE:

{% for helper in project.helper %}
    \e[0;32m{{ helper.name }}\e[0m
    {{ helper.info | default('') }}

{% endfor %}

    "
fi
