---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian9
  - distro: debian8
  - distro: ubuntu1804
  - distro: ubuntu1604

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/tschifftner/4078cf2a8429d967d5e100649ff2caa9/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh
  - ${DOCKER} bash -c "echo '127.0.0.1 magentodemo.local magento2demo.local' >> /etc/hosts"

  # Check autostart
  - ${DOCKER} systemctl --no-pager status nginx | grep 'nginx.service; enabled'
  - ${DOCKER} systemctl --no-pager status nginx | grep 'running'
  - ${DOCKER} systemctl --no-pager status php7.9-fpm | grep 'fpm.service; enabled'
  - ${DOCKER} systemctl --no-pager status php7.9-fpm | grep 'running'

  # Check awscli
  - ${DOCKER} cat /var/www/magentodemo/devbox/.aws/credentials | grep 'aws_secret_access_key=M1KDSFKSKDFJKKSDFNSINESFLSDKFSJDFSDFS'
  - ${DOCKER} cat /var/www/magento2demo/devbox/.aws/credentials | grep 'aws_secret_access_key=M2KDSFKSKDFJKKSDFNSINESFLSDKFSJDFSDFS'

  # Check databases
  - ${DOCKER} mysqlshow --user=magentodemo --password=magentodemo magentodemo
  - ${DOCKER} mysqlshow --user=magento2demo --password=magento2demo magento2demo

  # Check helper
  - ${DOCKER} magentodemo-devbox | grep 'magentodemo (devbox)'
  - ${DOCKER} magento2demo-devbox | grep 'magento2demo (devbox)'

  # Check mageruncodes
  - ${DOCKER} cat /etc/nginx/conf.d/mageruncodes.conf | grep -E magentodemo.local.*base;
  - ${DOCKER} cat /etc/nginx/conf.d/mageruncodes.conf | grep -E magentodemo.local.*website;
  - ${DOCKER} cat /etc/nginx/conf.d/mageruncodes.conf | grep -E magento2demo.local.*base;
  - ${DOCKER} cat /etc/nginx/conf.d/mageruncodes.conf | grep -E magento2demo.local.*website;

  # Check projectstorage
  - ${DOCKER} test -e /home/projectstorage/magentodemo/backup
  - ${DOCKER} test -e /home/projectstorage/magentodemo/devbox
  - ${DOCKER} test -e /home/projectstorage/magentodemo/production
  - ${DOCKER} ls -ald /home/projectstorage/magentodemo | grep -E 'drwxrwsr-x.*projectstorage projectstorage'

  - ${DOCKER} test -e /home/projectstorage/magento2demo/backup
  - ${DOCKER} test -e /home/projectstorage/magento2demo/devbox
  - ${DOCKER} test -e /home/projectstorage/magento2demo/production
  - ${DOCKER} ls -ald /home/projectstorage/magento2demo | grep -E 'drwxrwsr-x.*projectstorage projectstorage'

  # Check ssl
  ${DOCKER} ls -ald /var/www/magentodemo/devbox/.ssl | grep -E 'dr--r-----.*root www-data'
  ${DOCKER} ls -ald /var/www/magentodemo/devbox/.ssl/certificate.key | grep -E '-rw-r--r--.*root root'
  ${DOCKER} ls -ald /var/www/magentodemo/devbox/.ssl/certificate.crt | grep -E '-rw-r--r--.*root root'

  # Check ssh

  # Check folders magento2demo
  - ${DOCKER} test -e /var/www/magento2demo/devbox/logs
  - ${DOCKER} test -e /var/www/magento2demo/devbox/releases/current/htdocs
  - ${DOCKER} test -e /var/www/magento2demo/devbox/sessions
  - ${DOCKER} test -e /var/www/magento2demo/devbox/shared/media
  - ${DOCKER} test -e /var/www/magento2demo/devbox/shared/var
  - ${DOCKER} test -e /var/www/magento2demo/devbox/tmp

  # Check folders magentodemo
  - ${DOCKER} test -e /var/www/magentodemo/devbox/logs
  - ${DOCKER} test -e /var/www/magentodemo/devbox/releases/current/pub
  - ${DOCKER} test -e /var/www/magentodemo/devbox/sessions
  - ${DOCKER} test -e /var/www/magentodemo/devbox/shared/media
  - ${DOCKER} test -e /var/www/magentodemo/devbox/shared/var
  - ${DOCKER} test -e /var/www/magentodemo/devbox/tmp

  # Check folder permissions / acl (magentodemo)
  - ${DOCKER} ls -ald /var/www | grep -E 'drwxr-xr-x.*root root'
  - ${DOCKER} ls -ald /var/www/magentodemo | grep -E 'drwxr-sr-x.*root root'
  - ${DOCKER} ls -ald /var/www/magentodemo/devbox | grep -E 'drwxr-sr-x.*magentodemo www-data'
  - ${DOCKER} ls -ald /var/www/magentodemo/devbox/.aws | grep -E 'drwx------.*magentodemo www-data'
  - ${DOCKER} ls -ald /var/www/magentodemo/devbox/.ssh | grep -E 'drwx------.*magentodemo www-data'
  - ${DOCKER} ls -ald /var/www/magentodemo/devbox/shared | grep -E 'drwxrwsrwx.*magentodemo www-data'

  # Check folder permissions / acl (magento2demo)
  - ${DOCKER} ls -ald /var/www | grep -E 'drwxr-xr-x.*root root'
  - ${DOCKER} ls -ald /var/www/magento2demo | grep -E 'drwxr-sr-x.*root root'
  - ${DOCKER} ls -ald /var/www/magento2demo/devbox | grep -E 'drwxr-sr-x.*magento2demo www-data'
  - ${DOCKER} ls -ald /var/www/magento2demo/devbox/.aws | grep -E 'drwx------.*magento2demo www-data'
  - ${DOCKER} ls -ald /var/www/magento2demo/devbox/.ssh | grep -E 'drwx------.*magento2demo www-data'
  - ${DOCKER} ls -ald /var/www/magento2demo/devbox/shared | grep -E 'drwxrwsrwx.*magento2demo www-data'



after_failure:
  - ${DOCKER} nginx -v
  - ${DOCKER} curl http://magentodemo.local/
  - ${DOCKER} curl http://magento2demo.local/
  - ${DOCKER} service nginx status
  - ${DOCKER} service php7.0-fpm status
  - ${DOCKER} ansible --version

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
