---

- name: Ensure aws config folder exists
  file:
    path: ~/.aws
    state: directory
  when: project.awscli|length
  become: "{{ project.owner | default(project_default_owner) }}"


- name: Set aws config
  blockinfile:
    dest: ~/.aws/credentials
    marker: "# {mark} {{ item.profilename }}"
    #insertafter: "<body>"
    content: |
      [{{ item.profilename }}]
      {% for key, value in item.iteritems() %}
      {% if key != 'profilename' %}
      {{ key }}={{ value }}
      {% endif %}
      {% endfor %}

  when: project.awscli|length
  with_items: '{{ project.awscli }}'
  become: "{{ project.owner | default(project_default_owner) }}"
