---

- name: Protect programs to be overwritten by helpers
  assert:
    that:
#      - project.helper is defined
      - project.name != 'ansible'
      - project.name!= 'ansible-console'
      - project.name!= 'ansible-doc'
      - project.name!= 'ansible-galaxy'
      - project.name!= 'ansible-playbook'
      - project.name!= 'ansible-pull'
      - project.name!= 'ansible-vault'
      - project.name!= 'aws'
      - project.name!= 'composer'
      - project.name!= 'modman'
      - project.name!= 'n98-magerun'
      - project.name!= 'n98-magerun2'

- name: remove deprecated helper
  file:
    path: '/usr/local/bin/{{ project.name }}'
    state: absent

- name: create magento project helper
  template:
    src: 'helper/magento-helper.sh'
    dest: '/usr/local/bin/{{ project.name }}-{{ project.environment }}'
    mode: '0755'
  when: project.type is defined and project.type == 'magento' and project.awscli is defined
