---

- name: Ensure hosts file has needle
  lineinfile:
    dest: /etc/hosts
    regexp: '^# local hosts'
    line: '# local hosts'
    insertafter: 'EOF'

- name: Ensure devbox projects are written to hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.0.1 {{ project.server_alias }}'
    line: '127.0.0.1 {{ project.server_alias }}'
    insertafter: '^# local hosts'
