---

- name: 'Collect all magento run codes'
  set_fact:
    _project_mageruncodes: '{{ (_project_mageruncodes | default([])) + item.mageruncodes | list }}'
  when: (item.remove is not defined or item.remove != true)
  with_items: "{{ projects | selectattr('mageruncodes', 'defined') | list }}"

- name: Set magento run codes
  notify: reload nginx
  template:
    src: 'mageruncodes.conf'
    dest: '/etc/nginx/conf.d/'
    owner: root
    group: root
    mode: '0644'
  when: _project_mageruncodes is defined and _project_mageruncodes|length