---

- name: Handle requirements
  include: requirements.yml
  when: projects|length
  tags: ['projects-requirements']

- name: Handle databases
  include: databases.yml
  when: projects|length
  tags: ['projects-databases']

- name: Handle projectstorage
  include: projectstorage.yml
  when: projects|length
  tags: ['projects-storage']

- name: Handle ssl certificates
  include_tasks: ssl.yml
  tags: ['projects-ssl']
  when: projects|length and project.ssl_certificate is defined and (project.remove is not defined or project.remove != true)
  with_items: '{{ projects }}'
  loop_control:
    loop_var: project

- name: Normal Projects
  include: project/default.yml
  tags: ['projects-default']
  when: projects|length and (project.type is defined and project.type == 'default') and (project.remove is not defined or project.remove != true)
  with_items: '{{ projects }}'
  loop_control:
    loop_var: project

- name: Magento Projects
  include: project/magento.yml
  tags: ['projects-magento']
  when: projects|length and (project.type is defined and project.type == 'magento') and (project.remove is not defined or project.remove != true)
  with_items: '{{ projects }}'
  loop_control:
    loop_var: project

- name: Magento 2 Projects
  include: project/magento2.yml
  tags: ['projects-magento2']
  when: projects|length and (project.type is defined and project.type == 'magento2') and (project.remove is not defined or project.remove != true)
  with_items: '{{ projects }}'
  loop_control:
    loop_var: project

- name: Wordpress Projects
  include: project/wordpress.yml
  tags: ['projects-wordpress']
  when: projects|length and (project.type is defined and project.type == 'wordpress') and (project.remove is not defined or project.remove != true)
  with_items: '{{ projects }}'
  loop_control:
    loop_var: project

- name: Laravel Projects
  include: project/laravel.yml
  tags: ['projects-laravel']
  when: projects|length and (project.type is defined and project.type == 'laravel') and (project.remove is not defined or project.remove != true)
  with_items: '{{ projects }}'
  loop_control:
    loop_var: project

- name: Akeneo Projects
  include: project/akeneo.yml
  tags: ['projects-akeneo']
  when: projects|length and (project.type is defined and project.type == 'akeneo') and (project.remove is not defined or project.remove != true)
  with_items: '{{ projects }}'
  loop_control:
    loop_var: project

- name: Projects Cleanup
  include: project/cleanup.yml
  tags: ['projects-cleanup']
  when: projects|length and project.remove is defined and project.remove == true
  with_items: '{{ projects }}'
  loop_control:
    loop_var: project

- name: Handle awscli
  include: awscli.yml
  tags: ['projects-awscli']
  when: projects|length
  with_items: "{{ projects | selectattr('awscli', 'defined') | list }}"
  loop_control:
    loop_var: project

- name: Handle helper
  include: helper.yml
  tags: ['projects-helper']
  when: projects|length
  with_items: '{{ projects }}'
  loop_control:
    loop_var: project

- name: Handle ACL
  include: acl.yml
  tags: ['projects-acl']
  when: projects|length and project_set_acl
  with_items: "{{ projects | selectattr('name', 'defined') | list }}"
  loop_control:
    loop_var: project

- name: Handle mageruncodes
  include: mageruncodes.yml
  tags: ['projects-mageruncodes']
  when: projects|length

- name: Handle autostart
  include: autostart.yml
