---

- name: reload php5-fpm
  service:
    name: php5-fpm
    state: reloaded

- name: reload php7.0-fpm
  service:
    name: php7.0-fpm
    state: reloaded

- name: reload php7.1-fpm
  service:
    name: php7.1-fpm
    state: reloaded

- name: reload nginx
  command: nginx -t
  notify: _nginx_reload
  register: _nginx_reload

- name: _nginx_reload
  when: _nginx_reload
  service:
    name: nginx
    state: reloaded