---

- include: '_before.yml'

- name: Set default specific facts
  set_fact:
    project_snippet: 'default/php.conf'
    nginx_template: "{{ project.nginx_template | default('default/nginx.conf') }}"
    php_template: "{{ project.php_template | default('default/php5-fpm.conf') }}"
    dummy_path: '{{ project_dir }}/releases/build_dummy/htdocs/index.php'


- include: '_after.yml'
 