---

- include: '_before.yml'

- name: Set magento2 specific facts
  set_fact:
    project_snippet: 'magento2/magento2.conf'
    nginx_template: "{{ project.nginx_template | default('magento2/nginx.conf') }}"
    php_template: "{{ project.php_template | default('magento2/php5-fpm.conf') }}"
    dummy_path: '{{ project_dir }}/releases/build_dummy/pub/index.php'
    
- name: Create Magento 2 project structure
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ owner }}'
    group: '{{ group }}'
    mode: '{{ item.mode }}'
  with_items: #'{{ directories }}'
    - { path: '{{ project_dir }}/shared/media', mode: '02777' }
    - { path: '{{ project_dir }}/shared/var', mode: '02777' }
    - { path: '{{ project_dir }}/shared/var/log', mode: '02777' }
    # - { path: '{{ projectstorage_dir }}/{{ project.environment }}/shared/media', mode: '02777' }
    # - { path: '{{ projectstorage_dir }}/{{ project.environment }}/shared/var', mode: '02777' }
    # next should be separated in case several projects with different owners exists -> idempotence
    # - { path: '{{ projectstorage_dir }}/production', mode: '02777' }
    # - { path: '{{ projectstorage_dir }}/bin/deploy', mode: '02777' }

- name: Create project storage structure
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ project_storage_owner }}'
    group: '{{ project_storage_group }}'
    mode: '{{ item.mode }}'
    recurse: '{{ item.recurse | default(false) }}'
  with_items:
    - { path: '{{ projectstorage_dir }}/{{ project.environment }}/shared/media', mode: '02777' }
    - { path: '{{ projectstorage_dir }}/{{ project.environment }}/shared/var', mode: '02777' }
    - { path: '{{ projectstorage_dir }}/production', mode: '02777' }
    - { path: '{{ projectstorage_dir }}/bin/deploy', mode: '02777' }


- name: Create extra dummy project structure [magento2]
  file:
    path: '{{ project_dir }}/releases/build_dummy/pub/static'
    state: directory
    owner: '{{ owner }}'
    group: '{{ group }}'
    mode: '00775'
  when: _current_symlink.stat.islnk is not defined

- name: 'set 1. cronjob [magento2]'
  cron:
    name: '1. cronjob {{ project.name }} {{ project.environment }}'
    minute: '*/1'
    job: '(cd /var/www/{{ project.name }}/{{ project.environment }}/releases/current/ && /usr/bin/php bin/magento cron:run | grep -v "Ran jobs by schedule" >> var/log/magento.cron.log)'
    cron_file: '{{ project.name }}_{{ project.environment }}'
    user: '{{ owner }}'

- name: 'set 2. cronjob [magento2]'
  cron:
    name: '2. cronjob {{ project.name }} {{ project.environment }}'
    minute: '*/1'
    #job: '/usr/bin/php /var/www/{{ project.name }}/{{ project.environment }}/releases/current/update/cron.php [>> /log/file &]'
    job: '(cd /var/www/{{ project.name }}/{{ project.environment }}/releases/current/ && /usr/bin/php update/cron.php >> var/log/update.cron.log)'
    cron_file: '{{ project.name }}_{{ project.environment }}'
    user: '{{ owner }}'

- name: 'set 3. cronjob [magento2]'
  cron:
    name: '3. cronjob {{ project.name }} {{ project.environment }}'
    minute: '*/1'
    #job: '/usr/bin/php /var/www/{{ project.name }}/{{ project.environment }}/releases/current/bin/magento setup:cron:run [>> /log/file &'
    job: '(cd /var/www/{{ project.name }}/{{ project.environment }}/releases/current/ && /usr/bin/php bin/magento setup:cron:run >> var/log/setup.cron.log)'
    cron_file: '{{ project.name }}_{{ project.environment }}'
    user: '{{ owner }}'



- include: '_after.yml'