---

- include: '_before.yml'

- name: Set magento specific facts
  set_fact:
    project_snippet: 'magento/magento.conf'
    nginx_template: "{{ project.nginx_template | default('magento/nginx.conf') }}"
    php_template: "{{ project.php_template | default('magento/php5-fpm.conf') }}"
    logrotate_template: "{{ project.logrotate_template | default('magento/logrotate.conf') }}"

- name: Create project structure
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ owner }}'
    group: '{{ group }}'
    mode: '{{ item.mode }}'
    recurse: '{{ item.recurse | default(false) }}'
  with_items:
    - { path: '{{ project_dir }}/shared/media', mode: '02777' }
    - { path: '{{ project_dir }}/shared/var', mode: '02777' }

- name: Create project storage structure
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ project_storage_owner }}'
    group: '{{ project_storage_group }}'
    mode: '{{ item.mode }}'
    recurse: '{{ item.recurse | default(false) }}'
  with_items:
    - { path: '{{ projectstorage_dir }}/{{ project.environment }}/shared/media', mode: '02777' }
    - { path: '{{ projectstorage_dir }}/{{ project.environment }}/shared/var', mode: '02777' }
    - { path: '{{ projectstorage_dir }}/production', mode: '02777' }
    - { path: '{{ projectstorage_dir }}/bin/deploy', mode: '02777' }

- name: 'cronjob [magento]'
  cron:
    name: 'cronjob for {{ project.name }} {{ project.environment }}'
    minute: '*/1'
    #job: '! test -e {{ root_dir }}/maintenance.flag && ! test -e {{ root_dir }}/scheduler_cron.sh && test -e {{ root_dir }}/cron.sh && /bin/sh {{ root_dir }}/cron.sh'
    job: 'ROOT={{ root_dir }}; ! test -e ${ROOT}/maintenance.flag && ! test -e ${ROOT}/scheduler_cron.sh && test -e {{ root_dir }}/cron.sh && /bin/sh {{ root_dir }}/cron.sh'
    cron_file: '{{ project.name }}_{{ project.environment }}'
    user: '{{ owner }}'

- name: 'cronjob aoe_scheduler always [magento]'
  cron:
    name: 'cronjob aoe_scheduler always for {{ project.name }} {{ project.environment }}'
    minute: '*/1'
    #job: '! test -e {{ root_dir }}/maintenance.flag && test -e {{ root_dir }}/scheduler_cron.sh && {{ root_dir }}/scheduler_cron.sh && /bin/bash {{ root_dir }}/scheduler_cron.sh --mode always'
    job: 'ROOT={{ root_dir }}; ! test -e ${ROOT}/maintenance.flag && test -e ${ROOT}/scheduler_cron.sh && ${ROOT}/scheduler_cron.sh && /bin/bash ${ROOT}/scheduler_cron.sh --mode always'
    cron_file: '{{ project.name }}_{{ project.environment }}'
    user: '{{ owner }}'

- name: 'cronjob aoe_scheduler default [magento]'
  cron:
    name: 'cronjob aoe_scheduler default for {{ project.name }} {{ project.environment }}'
    minute: '*/1'
    job: 'ROOT={{ root_dir }}; ! test -e ${ROOT}/maintenance.flag && test -e ${ROOT}/scheduler_cron.sh && ${ROOT}/scheduler_cron.sh && /bin/bash ${ROOT}/scheduler_cron.sh --mode default'
    cron_file: '{{ project.name }}_{{ project.environment }}'
    user: '{{ owner }}'

- name: 'Logrotate Magento log files'
  template:
    src: '{{ logrotate_template }}'
    dest: '/etc/logrotate.d/{{ project.name }}_{{ project.environment }}'
    owner: root
    group: root
    mode: 0644

- include: '_after.yml'
